apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: ssh-container
        image: ncote/ubuntu-ssh:v12  # Updated version
        securityContext:
          capabilities:
            add:
                - SYS_CHROOT
                - SETUID
                - SETGID 
          # Add these to prevent audit/login issues
          runAsNonRoot: false
          allowPrivilegeEscalation: true
        env:
        - name: DEBUG_SSH
          value: "false"  # Disable debug to reduce noise
        - name: SSH_USER_NCOTE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-ssh-key
              key: ssh-key
        - name: SSH_USER_NCOTE_SHELL
          value: "/bin/bash"
        - name: SSH_USER_NCOTE_GROUPS
          value: "sudo"
        # Critical: Completely bypass login subsystem
        - name: SSH_CONFIG
          value: |
            LogLevel QUIET
            UsePAM no
            PrintLastLog no
            PrintMotd no
            UseDNS no
            X11Forwarding no
            Compression no
            # Force simple session without login recording
            ForceCommand /bin/bash -l
        ports:
        - containerPort: 22
        # Add resource limits to prevent issues
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"