apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: ssh-container
        image: lscr.io/linuxserver/openssh-server:latest
        ports:
        - containerPort: 2222
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: PUBLIC_KEY_FILE
          value: "/config/authorized_keys"
        - name: USER_NAME
          value: "sshuser"  # or {{ .Values.ssh.username | default "sshuser" }}
        - name: USER_PASSWORD_FILE
          value: "/dev/null"  # Disable password auth, keys only
        volumeMounts:
        - name: ssh-keys
          mountPath: /config
          readOnly: true
        - name: ssh-host-keys
          mountPath: /config/ssh_host_keys
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      volumes:
      - name: ssh-keys
        secret:
          secretName: {{ .Values.app.name }}-ssh-key
          items:
          - key: ssh-key
            path: authorized_keys
            mode: 0600
      - name: ssh-host-keys
        emptyDir: {}
      securityContext:
        runAsNonRoot: false  # SSH server needs to run as root initially
        fsGroup: 1000