apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: ssh-container
        image: ncote/ubuntu-ssh:v12
        securityContext:
          capabilities:
            add:
                - SYS_CHROOT
                - SETUID
                - SETGID 
          runAsNonRoot: false
          allowPrivilegeEscalation: true
        env:
        - name: DEBUG_SSH
          value: "true"
        - name: SSH_USER_NCOTE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-ssh-key
              key: ssh-key
        - name: SSH_USER_NCOTE_SHELL
          value: "/bin/bash"
        - name: SSH_USER_NCOTE_GROUPS
          value: "sudo"
        - name: SSH_CONFIG
          value: |
            LogLevel DEBUG3
            UsePAM no
            UseLogin no
            PrintLastLog no
            PrintMotd no
            UseDNS no
        ports:
        - containerPort: 22