apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-ssh
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-ssh
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-ssh
    spec:
      containers:
      - name: ssh-server
        image: lscr.io/linuxserver/openssh-server:latest
        ports:
        - containerPort: 2222
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: PASSWORD_ACCESS
          value: "true"
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-ssh-key
              key: username
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-ssh-key
              key: password
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi