apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: ssh-container
        image: ncote/ubuntu-ssh:v14  # Updated version
        securityContext:
          capabilities:
            add:
                - SYS_CHROOT
                - SETUID
                - SETGID 
          # Add these to prevent audit/login issues
          runAsNonRoot: false
          allowPrivilegeEscalation: true
        env:
        - name: DEBUG_SSH
          value: "true"
        - name: SSH_USER_NCOTE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-ssh-key
              key: ssh-key
        - name: SSH_USER_NCOTE_SHELL
          value: "/bin/bash"
        - name: SSH_USER_NCOTE_GROUPS
          value: "sudo"  # The entrypoint script will create this group
        # Disable audit and login systems that cause container issues
        - name: AUDIT_DISABLED
          value: "1"
        - name: SSH_CONFIG
          value: |
            LogLevel DEBUG3
            UsePAM no
            PrintLastLog no
            PrintMotd no
            UseDNS no
            # Force disable all session recording
            X11Forwarding no
            # Disable compression to reduce complexity
            Compression no
        ports:
        - containerPort: 22
        # Add resource limits to prevent issues
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"