apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.app.secret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.app.name }}-secrets
  data:
    - secretKey: {{ .Values.app.name }}-username
      remoteRef:
        key: {{ .Values.app.secret.path }}
        property: {{ .Values.app.secret.usernameKey }}
    - secretKey: {{ .Values.app.name }}-password
      remoteRef:
        key: {{ .Values.app.secret.path }}
        property: {{ .Values.app.secret.passwordKey }}