apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-external
  namespace: {{ .Release.Namespace }}
  labels:
    cirrus/lb: internal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.app.name }}.k8s.ucar.edu"
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP